# Generated by Django 3.2.4 on 2021-10-05 12:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_alter_itemm_product'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('orders', '0002_rename_orderm_ordersm'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordersm',
            name='itemname',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_itemname', to='products.itemm'),
        ),
        migrations.AlterField(
            model_name='ordersm',
            name='price',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_price', to='products.itemm'),
        ),
        migrations.AlterField(
            model_name='ordersm',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
