# Generated by Django 3.2.4 on 2021-10-05 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_itemm_imgaddress'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemm',
            name='imgAddress',
            field=models.CharField(default='https://previews.123rf.com/images/yaroslav2077/yaroslav20772002/yaroslav2077200200012/140498347-phone-icon-vector-call-icon-vector-mobile-phone-smartphone-device-gadget-telephone-icon.jpg', max_length=255),
        ),
    ]
