# Generated by Django 3.2.4 on 2021-10-05 05:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_alter_itemm_imgaddress'),
    ]

    operations = [
        migrations.RenameField(
            model_name='itemm',
            old_name='item',
            new_name='item_name',
        ),
        migrations.AlterField(
            model_name='itemm',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item_details', to='products.productm'),
        ),
    ]
