# Generated by Django 3.2.4 on 2021-10-05 05:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_auto_20211005_1035'),
    ]

    operations = [
        migrations.RenameField(
            model_name='itemm',
            old_name='item_name',
            new_name='item',
        ),
    ]
