# Generated by Django 3.2.4 on 2021-10-05 05:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_rename_item_name_itemm_item'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itemm',
            name='product',
        ),
        migrations.AddField(
            model_name='itemm',
            name='product_name',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='product_name', to='products.productm'),
            preserve_default=False,
        ),
    ]
