# Generated by Django 3.2.4 on 2021-10-05 05:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_auto_20211005_1100'),
    ]

    operations = [
        migrations.RenameField(
            model_name='itemm',
            old_name='product_name',
            new_name='product',
        ),
    ]
